apiVersion: v1
kind: Service
metadata:
  name: dojo-frontend
  namespace: dojo
  labels:
    app: dojo-frontend
spec:
  selector:
    app: dojo-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
